AnotherCity/Models/Project.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace AnotherCity.Models
{
    public partial class Project
    {
        public Project()
        {
            Images = new HashSet<Image>();
            InvestOpportunities = new HashSet<InvestOpportunity>();
            VolunteerOpportunities = new HashSet<VolunteerOpportunity>();
        }

        public int Id { get; set; }
        [Required]
        public int? MemberId { get; set; }
        [Required]
        [Display(Name = "Title")]
        public string Title { get; set; }
        [Display(Name = "Volunteers?")]
        public bool VolunteerOpp { get; set; }
        [Display(Name = "Investors?")]
        public bool InvestOpp { get; set; }

        [Required]
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy hh:mm tt}", ApplyFormatInEditMode = true)]
        [Display(Name = "Start")]
        public DateTime? StartDate { get; set; }

        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name = "Finish")]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy hh:mm tt}", ApplyFormatInEditMode = true)]
        public DateTime? FinishDate { get; set; }
        [Required]
        [MinLength(5)]
        [MaxLength(128)]
        [Display(Name = "Short description")]
        public string ShortDesc { get; set; }
        [Required]
        [MinLength(5)]
        [MaxLength(4096)]
        [Display(Name = "Description")]
        public string Description { get; set; }
        [Display(Name = "Main image")]
        public string MainImg { get; set; }
        [Required]
        [Display(Name = "Location")]
        public string Location { get; set; }
        [Display(Name = "Map Location")]
        public string LatLng { get; set; }
        [Display(Name = "Social Links")]
        public string SocialLinks { get; set; }

        [Required]
        [Display(Name = "Status")]
        public string Status { get; set; }

        [Display(Name = "Featured?")]
        public bool Featured { get; set; }

        [Display(Name = "Fotos")]
        public virtual ICollection<Image> Images { get; set; }
        [Display(Name = "Volunteers")]
        public virtual ICollection<InvestOpportunity> InvestOpportunities { get; set; }
        [Display(Name = "Investors")]
        public virtual ICollection<VolunteerOpportunity> VolunteerOpportunities { get; set; }
        [Display(Name = "Responsible")]
        public virtual Member Member { get; set; }
        public ICollection<ProjectSocials> ProjectSocials { get; set; }

    }
}

AnotherCity/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AnotherCity.Data;
using AnotherCity.Models;
using AnotherCity.Utilities;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;

namespace AnotherCity.Controllers
{
    
    public class ProjectsController : Controller
    {
        private readonly AnotherCityDbContext _context;
        private readonly IStringLocalizer<ProjectsController> _localizer;

        public ProjectsController(AnotherCityDbContext context,IStringLocalizer<ProjectsController> localizer)
        {
            _context = context;    
            _localizer = localizer;
        }
        
        
        // GET: Projects
        [Authorize]
        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["TitleSortParm"] = String.IsNullOrEmpty(sortOrder) ? "title_desc" : "";
            ViewData["DateSortParm"] = sortOrder == "date" ? "date_desc" : "date";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            var projects = from s in _context.Projects.Include(p => p.Member)
                             select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                projects = projects.Where(s => s.Title.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "title":
                    projects = projects.OrderBy(s => s.Title);
                    break;
                case "title_desc":
                    projects = projects.OrderByDescending(s => s.Title);
                    break;
                case "date":
                    projects = projects.OrderBy(s => s.StartDate);
                    break;
                default:
                    projects = projects.OrderByDescending(s => s.StartDate);
                    break;
            }
            // var anotherCityDbContext = _context.Volunteers.Include(v => v.Account).Include(v => v.VolunteerOpportunity);
            int pageSize = 10;
            return View(await PaginatedList<Project>.CreateAsync(projects.AsNoTracking(), page ?? 1, pageSize));
        }

        // GET: Projects/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Projects
                .Include(p => p.Member)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        // GET: Projects/Create
        [Authorize]
        public IActionResult Create()
        {
            ViewData["MemberId"] = new SelectList(_context.Members, "Id", "LastName");
            return View();
        }

        // POST: Projects/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ICollection<IFormFile> images,IFormFile MainImg,[Bind("Id,Featured,MemberId,Title,VolunteerOpp,InvestOpp,StartDate,FinishDate,ShortDesc,Description,Location,LatLng,SocialLinks,Status")] Project project)
        {
            if (ModelState.IsValid)
            {
                // Image upload --- rewrite with good structure
                if (MainImg != null)
                {
                    long size = MainImg.Length;
                    // full path to file in temp location
                    var filePath = Path.Combine("wwwroot/uploads/", MainImg.FileName);
                    if (MainImg.Length > 0)
                    {
                        using (var stream = new FileStream(filePath, FileMode.Create))
                        {
                            await MainImg.CopyToAsync(stream);
                        }
                    }

                    //Database save
                    project.MainImg = MainImg.FileName;
                }
                
                _context.Add(project);
                await _context.SaveChangesAsync();
                
                if(project.VolunteerOpp)
                {
                    VolunteerOpportunity task = new VolunteerOpportunity();
                    task.JobType = "Help";
                    task.ProjectId = project.Id;
                    task.Title = project.Title + " hepl!";
                    _context.Add(task);
                    await _context.SaveChangesAsync();
                }

                if (images != null)
                {

                    foreach (var img in images)
                    {
                        var filePath = Path.Combine("wwwroot/uploads/", img.FileName);

                        if (img.Length > 0)
                        {
                            using (var fileStream = new FileStream(filePath, FileMode.Create))
                            {
                                await img.CopyToAsync(fileStream);
                                Image tmpImg = new Image();
                                tmpImg.Name = "Image";
                                tmpImg.Path = img.FileName;
                                tmpImg.ProjectId = project.Id;
                                _context.Images.Add(tmpImg);
                                await _context.SaveChangesAsync();

                            }
                        }

                    }
                }
                return RedirectToAction("Index");
            }
            ViewData["MemberId"] = new SelectList(_context.Members, "Id", "LastName", project.MemberId);
            return View(project);
        }

        // GET: Projects/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.Projects
                .Include(i => i.Images)
                .Include(m => m.ProjectSocials)
                    .ThenInclude(ms => ms.Social)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (project == null)
            {
                return NotFound();
            }
            ViewData["MemberId"] = new SelectList(_context.Members, "Id", "LastName", project.MemberId);
            ViewData["SocialId"] = new SelectList(_context.SocialServices, "Id", "Title");
            return View(project);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ICollection<IFormFile> images, IFormFile MainImg, int id, [Bind("Id,Featured,MemberId,Title,VolunteerOpp,InvestOpp,StartDate,FinishDate,ShortDesc,Description,Location,LatLng,SocialLinks,Status")] Project project)
        {
            if (id != project.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    // Image upload --- rewrite with good structure
                    if(MainImg!=null)
                    { 
                        long size = MainImg.Length;
                        // full path to file in temp location
                        var filePath = Path.Combine("wwwroot/uploads/", MainImg.FileName);
                        if (MainImg.Length > 0)
                        {
                            using (var stream = new FileStream(filePath, FileMode.Create))
                            {
                                await MainImg.CopyToAsync(stream);
                            }
                        }

                        //Database save
                        project.MainImg = MainImg.FileName;
                    }
                    else
                    {
                        project.MainImg = (await _context.Projects.AsNoTracking().SingleOrDefaultAsync(m => m.Id == id)).MainImg;
                    }
                    _context.Update(project);
                    await _context.SaveChangesAsync();
                  
                    if (project.VolunteerOpp && _context.VolunteerOpportunities.Any(opp => opp.ProjectId == project.Id))
                    {
                        VolunteerOpportunity task = new VolunteerOpportunity();
                        task.JobType = "Help";
                        task.ProjectId = project.Id;
                        task.Title = project.Title+" hepl!";
                        _context.Add(task);
                        await _context.SaveChangesAsync();
                    }

                    if (images != null)
                    {

                        foreach (var img in images)
                        {
                            var filePath = Path.Combine("wwwroot/uploads/", img.FileName);

                            if (img.Length > 0)
                            {
                                using (var fileStream = new FileStream(filePath, FileMode.Create))
                                {

AnotherCity/Views/Projects/Delete.cshtml
@model AnotherCity.Models.Project

@{
    ViewData["Title"] = "Delete Project";
    Layout = "~/Views/Shared/_BackendLayout.cshtml";
}

<h2>@ViewData["Title"]</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <input type="hidden" asp-for="Id" />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.VolunteerOpp)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.VolunteerOpp)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.InvestOpp)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.InvestOpp)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FinishDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FinishDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ShortDesc)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ShortDesc)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MainImg)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MainImg)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LatLng)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LatLng)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Member)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Member.LastName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

AnotherCity/Views/Projects/Details.cshtml
@model AnotherCity.Models.Project

@{
    ViewData["Title"] = "Details of Project";
    Layout = "~/Views/Shared/_BackendLayout.cshtml";
}

<h2>@ViewData["Title"]</h2>

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.VolunteerOpp)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.VolunteerOpp)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.InvestOpp)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.InvestOpp)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FinishDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FinishDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ShortDesc)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ShortDesc)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MainImg)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MainImg)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LatLng)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LatLng)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Member)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Member.LastName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

AnotherCity/Views/Projects/Index.cshtml
@model AnotherCity.Utilities.PaginatedList<AnotherCity.Models.Project>

@{
    ViewData["Title"] = "Projects Administration";
    Layout = "~/Views/Shared/_BackendLayout.cshtml";
}

<h2>@ViewData["Title"]</h2>

<p>
    <a asp-action="Create">Create New Project   </a>
</p>
<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Find by name: <input type="text" name="SearchString" value="@ViewData["currentFilter"]" />
            <input type="submit" value="Search" class="btn btn-default" /> |
            <a asp-action="Index">Back to Full List</a>
        </p>
    </div>
</form>
<table class="table">
    <thead>
        <tr>
                <th>
                    <a asp-action="Index" asp-route-sortOrder="@ViewData["TitleSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">@Html.DisplayNameFor(model => model.FirstOrDefault().Title)</a>
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FirstOrDefault().VolunteerOpp)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FirstOrDefault().InvestOpp)
                </th>
                <th>
                    <a asp-action="Index" asp-route-sortOrder="@ViewData["DateSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">@Html.DisplayNameFor(model => model.FirstOrDefault().StartDate)</a>
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FirstOrDefault().FinishDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FirstOrDefault().Location)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FirstOrDefault().Status)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FirstOrDefault().Member)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VolunteerOpp)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.InvestOpp)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FinishDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Member.LastName)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-page="@(Model.PageIndex - 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @prevDisabled">
    Previous
</a>
<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-page="@(Model.PageIndex + 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @nextDisabled">
    Next
</a>

AnotherCity/Views/Projects/IndexAll.cshtml
@model IEnumerable<AnotherCity.Models.Project>
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

@{
    ViewData["Title"] = Localizer["Projects_Title"];
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="bg-gray no-padding below-header">
    <div class="container">
        <div class="row">
            
            @if (Model.Where(d => d.Featured==true).Count() != 0)
            {
                <h3 class="hidden-lg hidden-md hidden-sm title-med text-center">@Localizer["Projects_Featured"]</h3>
                @await Html.PartialAsync("_SliderItems", Model.Where(d =>d.Featured==true).OrderBy(s => s.FinishDate))
            }
            @if (Model.Where(d => ((d.StartDate.Value.Month - DateTime.Now.Month) + 12 * (d.StartDate.Value.Year - DateTime.Now.Year)) > 1 && d.Featured==false).Count() != 0)
            {
                <h3 class="hidden-lg hidden-md hidden-sm title-med  text-center">@Localizer["Projects_Current"]</h3>
                @await Html.PartialAsync("_RightItems", Model.Where(d => ((d.StartDate.Value.Month - DateTime.Now.Month) + 12 * (d.StartDate.Value.Year - DateTime.Now.Year)) > 1 && d.Featured == false).OrderBy(s => s.StartDate))
            }
        </div>
    </div>
</section>
@if (Model.Where(d => ((d.StartDate.Value.Month - DateTime.Now.Month) + 12 * (d.StartDate.Value.Year - DateTime.Now.Year)) <= 1 && d.Featured == false).Count() != 0)
{
    <section id="blog" class="bg-gray">
        <div class="container">
            <h3 class="hidden-lg hidden-md hidden-sm title-med text-center">@Localizer["Projects_Past"]</h3>
            @await Html.PartialAsync("_BottomItems", Model.Where(d => ((d.StartDate.Value.Month - DateTime.Now.Month) + 12 * (d.StartDate.Value.Year - DateTime.Now.Year)) <= 1 && d.Featured == false).OrderByDescending(s => s.StartDate))
        </div>
    </section>
}

AnotherCity/Views/Projects/IndexSome.cshtml
@model IEnumerable<AnotherCity.Models.Project>
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!-- head section -->
<section class="page-title border-bottom-light border-top-light ">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-7 col-sm-12 center-col wow slideInUp wow fadeInUp" data-wow-duration="300ms">
                <!-- page title -->
                <h1 class="black-text text-center">@ViewData["Title"]</h1>
                <!-- end page title -->
                <!-- page title tagline -->
                <span class="xs-display-none">@Localizer["Projects_LearnMore"]</span>
                <!-- end title tagline -->
                <div class="separator-line margin-three bg-black no-margin-lr sm-margin-top-three sm-margin-bottom-three no-margin-bottom xs-display-none"></div>
            </div>
        </div>
    </div>
</section>
<!-- end head section -->

<section id="blog" class="bg-gray no-padding ">
    <div class="container result-can-be-empty">
        @if (Model.Count() > 0)
        {
            @await Html.PartialAsync("_BottomItems", Model)
        }
        else
        { 
            <div class="empty-result">
                <h4 class="text-center">@Localizer["Projects_LearnMore"]</h4>
            </div>
        }
    </div>
</section>

AnotherCity/Views/Projects/_BottomItems.cshtml
@model IEnumerable<AnotherCity.Models.Project>
@inject AnotherCity.Services.FormattingService Format

<div class="row blog-grid-listing">
    @foreach (var item in Model)
    {
        <div class="col-md-4 col-sm-6 col-xs-6 blog-listing wow fadeInUp" data-wow-duration="300ms">
            <div class="blog-image">
                <a asp-controller="Projects" asp-action="ViewProject" asp-route-id="@item.Id">
                    <img src="~/uploads/@item.MainImg" alt="" />
                    @*<img src="http://via.placeholder.com/1020x720" alt="" />*@
                </a>
            </div>
            <div class="blog-details">
                <div class="blog-date">
                    @*Hosted by <a asp-controller="Members" asp-action="IndexAll">@item.Member.FirstName @item.Member.LastName</a> | *@
                    @Format.AsReadableDate(item.StartDate)
                </div>
                <div class="blog-title"><a asp-controller="Projects" asp-action="ViewProject" asp-route-id="@item.Id" class="to-be-translated">@item.Title</a></div>
                <div class="blog-short-description to-be-translated" >@item.ShortDesc</div>
                @*<div class="separator-line bg-black no-margin-lr"></div>
                <div><a href="#" class="blog-like"><i class="fa fa-heart-o"></i>Likes</a><a href="#" class="blog-share"><i class="fa fa-share-alt"></i>Share</a><a href="#" class="comment"><i class="fa fa-comment-o"></i>3 comment(s)</a></div>*@
            </div>
        </div>
    }
</div>

AnotherCity/Views/Projects/_RightItems.cshtml
@model IEnumerable<AnotherCity.Models.Project>
@inject AnotherCity.Services.FormattingService Format

<div class="col-md-4">
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="blog-slider-right col-md-12 col-sm-6 col-xs-12 wow fadeInUp" data-wow-duration="600ms">

                <div class="blog-slider-grid">
                    <figure>
                        <a asp-controller="Projects" asp-action="ViewProject" asp-route-id="@item.Id">
                            <img src="~/uploads/@item.MainImg" alt="" />
                            @*<img src="http://via.placeholder.com/1020x720" alt="" />*@
                        </a>
                        <figcaption>
                            <h3><a asp-controller="Projects" asp-action="ViewProject" asp-route-id="@item.Id" class="to-be-translated">@item.Title</a></h3>
                            <span>@Format.AsReadableDate(item.StartDate)</span>
                        </figcaption>
                    </figure>
                </div>
            </div>
        }
    </div>
</div>

AnotherCity/Views/Projects/_SliderItems.cshtml
@model IEnumerable<AnotherCity.Models.Project>
@inject AnotherCity.Services.FormattingService Format


<div class="col-md-8 hidden-xs">
    <div id="blog-slider-grid" class="owl-carousel owl-theme">
        @foreach (var item in Model)
        {
            <div class="item">
                <div class="blog-slider-grid">
                    <figure>
                        <a asp-controller="Projects" asp-action="ViewProject" asp-route-id="@item.Id">
                            <img src="~/uploads/@item.MainImg" alt="" />
                            @*<img src="http://via.placeholder.com/1020x720" alt="" />*@
                        </a>
                        <figcaption>
                            <h3><a asp-controller="Projects" asp-action="ViewProject" asp-route-id="@item.Id" class="to-be-translated"> @item.Title</a></h3>
                            <span>
                                @*Hosted by <a asp-controller="Members" asp-action="IndexAll">@item.Member.FirstName @item.Member.LastName</a> |*@
                                @Format.AsReadableDate(item.StartDate)
                            </span>
                            <p class="to-be-translated">@item.ShortDesc</p>
                        </figcaption>
                    </figure>
                </div>
            </div>
        }
    </div>
</div>

<div class=" hidden-lg hidden-md hidden-sm col-md-8">
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="blog-slider-right col-md-12 col-sm-6 col-xs-12 wow fadeInUp" data-wow-duration="600ms">

                <div class="blog-slider-grid">
                    <figure>
                        <a asp-controller="Projects" asp-action="ViewProject" asp-route-id="@item.Id">
                            <img src="~/uploads/@item.MainImg" alt="" />
                            @*<img src="http://via.placeholder.com/1020x720" alt="" />*@
                        </a>
                        <figcaption>
                            <h3><a asp-controller="Projects" asp-action="ViewProject" asp-route-id="@item.Id"  class="to-be-translated">@item.Title</a></h3>
                            <span>@Format.AsReadableDate(item.StartDate)</span>
                        </figcaption>
                    </figure>
                </div>
            </div>
        }
    </div>
</div>